version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - /docker_conf/rabbitmq/data/:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
    restart: always
    networks:
      - ambev-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    restart: always
    networks:
      - ambev-network

  # postgres:
  #   image: postgres
  #   container_name: postgres
  #   hostname: "postgres"
  #   restart: always
  #   volumes:
  #     - type: tmpfs
  #       target: /dev/shm
  #       tmpfs:
  #         size: 134217728 # 128*2^20 bytes = 128Mb
  #   environment:
  #     POSTGRES_USER: "docker"
  #     POSTGRES_PASSWORD: "docker"
  #   ports:
  #     - "5432:5432"
  #   expose:
  #     - 5432
  #   networks:
  #     - ambev-network

volumes:
  logs-folder:
    name: ${log_rabbitmq_management}
    driver: local
  mongodb_data:
    driver: local

networks:
  ambev-network:
    name: ambev-network
    driver: bridge
